# Generated by Django 4.2.30 on 2026-08-30 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255, unique=True)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('taxon_rank', models.CharField(blank=True, max_length=50, null=True)),
                ('taxonomy_data', models.JSONField(default=dict, help_text='Hierarchy: Kingdom, Phylum, Class, Order, Family, Genus')),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('salinity_min', models.FloatField(blank=True, null=True)),
                ('salinity_max', models.FloatField(blank=True, null=True)),
                ('chlorophyll_min', models.FloatField(blank=True, null=True)),
                ('chlorophyll_max', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='OBIS', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FisheriesOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='OBIS', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='fisheries.species')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='fisheries_f_timesta_11fe79_idx'), models.Index(fields=['latitude', 'longitude'], name='fisheries_f_latitud_d5e4f8_idx')],
            },
        ),
    ]
