# Generated by Django 4.2.30 on 2026-08-30 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OceanObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.FloatField(help_text='Sea Surface Temperature in Celsius')),
                ('salinity', models.FloatField(help_text='Salinity in PSU')),
                ('chlorophyll', models.FloatField(help_text='Chlorophyll concentration in mg/m3')),
                ('depth', models.FloatField(default=0.0, help_text='Depth in meters')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('source', models.CharField(default='Copernicus', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='ocean_ocean_timesta_2dda3f_idx'), models.Index(fields=['latitude', 'longitude'], name='ocean_ocean_latitud_bacaca_idx')],
            },
        ),
    ]
