# Generated by Django 4.2.30 on 2026-08-30 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter', models.CharField(help_text='e.g., temperature, salinity, chlorophyll', max_length=50)),
                ('observed_value', models.FloatField()),
                ('expected_value', models.FloatField(help_text='Expected baseline/normal value')),
                ('severity', models.CharField(default='Low', help_text='Low, Medium, High', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('model_method', models.CharField(default='Isolation Forest', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(help_text='e.g., temperature, salinity, chlorophyll, suitability, risk', max_length=50)),
                ('target_id', models.CharField(blank=True, help_text='e.g., species id, region id, or coordinates', max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('prediction_date', models.DateField()),
                ('predicted_value', models.FloatField()),
                ('features_used', models.JSONField(blank=True, default=dict, null=True)),
                ('model_version', models.CharField(default='1.0.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['prediction_date'], name='ai_aipredic_predict_44d887_idx'), models.Index(fields=['target_type', 'target_id'], name='ai_aipredic_target__3a9cc0_idx')],
            },
        ),
    ]
