# Generated by Django 4.2.30 on 2026-08-30 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodiversityIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('species_count', models.IntegerField(default=0)),
                ('occurrence_count', models.IntegerField(default=0)),
                ('shannon_index', models.FloatField(blank=True, help_text='AI-derived/model-derived species diversity index', null=True)),
                ('risk_score', models.FloatField(default=0.0, help_text='AI-derived biodiversity risk score (0 to 100%)')),
                ('risk_level', models.CharField(default='Low', help_text='Low, Moderate, High', max_length=20)),
                ('observation_period', models.CharField(default='2020-2026', max_length=100)),
                ('source', models.CharField(default='AI Model', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biodiversity_indicators', to='ocean.region')),
            ],
        ),
    ]
